name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello world action step
        uses: mrkkrp/ormolu-action@master
        with:
          who-to-greet: 'Mona the Octocat'
